stages:
  - build

build_project:
  stage: build
  script:
    - rm -rf DerivedData
    - xcodebuild -sdk iphonesimulator -derivedDataPath DerivedData -workspace RSSReader.xcworkspace -scheme AllTests-iOS -destination 'platform=iOS Simulator,name=iPhone X,OS=latest' -enableCodeCoverage YES test CODE_SIGNING_REQUIRED=NO
