disabled_rules:
  - force_cast
  - force_try
  - type_name
  - unused_closure_parameter
  - discarded_notification_center_observer
  - colon
  - trailing_whitespace
  - opening_brace
  - mark
  - void_return
  - statement_position
  - unused_optional_binding
  - weak_delegate
  - cyclomatic_complexity
  - large_tuple
  - implicit_getter
  - nesting
  - redundant_optional_initialization
  - for_where
  - empty_parentheses_with_trailing_closure
  - fallthrough
  - identifier_name
excluded:
  - Pods
  - GitSubtrees
  - RSSReader/RSSReader/R.generated.swift
line_length: 300
identifier_name:
  min_length: 1
  max_length: 60
  excluded:
    - keyPathsForValues
file_length: 500
