osx_image: xcode9.2
language: objective-c
env:
  matrix:
  - sdk=iphonesimulator destination='platform=iOS Simulator,name=iPhone X,OS=11.2'
  - sdk=macosx destination='platform=macOS'
script:
- xcodebuild -sdk "${sdk:?}" -project GETracing.xcodeproj -scheme GETracing -destination "${destination:?}" test CODE_SIGNING_REQUIRED=NO TEST_HOST=
