// Automatically generated by swiftrsrc. Do not edit.

struct MainStoryboard {
	struct StoryboardIdentifiers {
		static let ItemSummaryWeb = "ItemSummaryWeb"
		static let MainTabBar = "MainTabBar"
	}
	struct ReuseIdentifiers {
		static let Folder = "Folder"
		static let Subscription = "Subscription"
	}
	struct SegueIdentifiers {
		static let ShowListPages = "showListPages"
		static let ShowListArticle = "showListArticle"
		static let ShowHistoryArticle = "showHistoryArticle"
		static let ShowHistoryPages = "showHistoryPages"
		static let ShowFolder = "showFolder"
		static let ShowSubscription = "showSubscription"
		static let ShowCombined = "showCombined"
		static let ShowSubscriptions = "showSubscriptions"
		static let ShowFavorites = "showFavorites"
		static let ShowHistory = "showHistory"
		static let ShowDebug = "showDebug"
	}
}
