// Automatically generated by swiftrsrc. Do not edit.

struct MainStoryboard {
	struct StoryboardIdentifiers {
		static let ItemSummaryWeb = "itemSummaryWeb"
	}
	struct ReuseIdentifiers {
		static let Item = "Item"
		static let HistoryItem = "HistoryItem"
		static let Folder = "Folder"
		static let Subscription = "Subscription"
	}
	struct SegueIdentifiers {
		static let ShowPages = "showPages"
		static let ShowFolder = "showFolder"
		static let ShowSubscription = "showSubscription"
	}
}
