#! /bin/sh -ex

#  ItemTableViewCell-Generate
#  RSSReader
#
#  Created by Grigory Entin on 09.10.16.
#  Copyright © 2016 Grigory Entin. All rights reserved.

wd=$(dirname "$0")
for i in $(seq 0 6)
do
	sed 's/reuseIdentifier="Item"/reuseIdentifier="Item'-$i'"/' < "${wd:?}"/../ItemTableViewCell.xib > "${wd:?}"/ItemTableViewCell-$i.xib
done
