#! /bin/sh -xe

srcRootDir="${1:?}"; shift

find "${srcRootDir:?}" -name '*.xcodeproj' -not \( -path './Pods/*' -o -path './vendor/*' -o -path './GitSubtrees/*' \) -exec ./XcodeSupport/CreateOrUpdateEmbedSourcesBuildPhaseForMainTarget '{}' \;
