#! /bin/sh -xe

srcRootDir="${1:?}"; shift

pushd "${srcRootDir:?}"
find . -name '*.xcodeproj' -not \( -path './Pods/*' -o -path './vendor/*' -o -path './GitSubtrees/*' \) -exec ./XcodeSupport/CreateOrUpdateEmbedSourcesBuildPhaseForMainTarget '{}' \;
popd
