#!/bin/sh -e

#  VersionIsClean
#  RSSReader
#
#  Created by Grigory Entin on 08.09.16.
#  Copyright © 2016 Grigory Entin. All rights reserved.

status=$(git -C "${SRCROOT:?}" status -s)
test "z${status}" == "z"
