#! /bin/sh -ex

#  XCRegenerateSBConstantsSwift.sh
#  RSSReader
#
#  Created by Grigory Entin on 11.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

if [ -x ~/.gem/bin/sbconstants ]
then

export GEM_HOME="${HOME:?}"/.gem
export GEM_PATH="${HOME:?}"/.gem

~/.gem/bin/sbconstants --swift "${SRCROOT:?}/${TARGET_NAME:?}"/SBConstants.swift "${SRCROOT:?}/${TARGET_NAME:?}"/Base.lproj/Main.storyboard

fi
