#! /bin/bash -xe

xcov_reports="${tmpdir:?}/xcov_reports"

# shellcheck disable=SC2016
workspace=$(sed -n 's/^Pods workspace available at `\(.*\)` for inspection.$/\1/gp' < "${pod_lib_lint_no_clean_log:?}")

bundle exec xcov -w "${workspace:?}" -o "${xcov_reports:?}"

bash <(curl -s https://codecov.io/bash) -D "${ddp:?}"
