#! /bin/bash

set -exo pipefail

if false
then
# shellcheck disable=SC2016
workspace=$(sed -n 's/^Pods workspace available at `\(.*\)` for inspection.$/\1/gp' < "${pod_lib_lint_no_clean_log:?}")
xcov_reports="${tmpdir:?}/xcov_reports"
bundle exec xcov -w "${workspace:?}" -o "${xcov_reports:?}" --verbose --coveralls_service_name travis-ci --coveralls_service_job_id "${TRAVIS_JOB_ID:?}"
fi

if true
then
bash <(curl -s https://codecov.io/bash) -D ~/Library/Developer/Xcode/DerivedData/
fi

set +exo pipefail
