#! /bin/sh -xe

#  EmbedStaticLinkAwareDynamicFrameworks
#  GEXcodeBuildPhases
#
#  Created by Grigory Entin on 11.01.2018.
#  Copyright (c) 2018 Grigory Entin. All rights reserved.

rsync -urtlv "${TARGET_BUILD_DIR:?}"/"${GE_DYNAMIC_FRAMEWORKS_COLLECTOR_FOLDER_PATH:?}"/ "${TARGET_BUILD_DIR:?}/${FRAMEWORKS_FOLDER_PATH:?}"/
