#! /bin/sh -e

bn=$(basename "$0")
wd=$(dirname "$0")

tmpdir=$(mktemp -d /tmp/"${bn:?}".XXXXX)

sourcesList="${tmpdir:?}"/Sources.list

"${wd:?}"/../XcodeSupport/ListXcodeProjectTargetSources "${PROJECT_FILE_PATH:?}" "${TARGET_NAME:?}" > "${sourcesList:?}"

sourcesResourcesDir="${TARGET_BUILD_DIR:?}/${UNLOCALIZED_RESOURCES_FOLDER_PATH:?}/Sources"
test -d "${sourcesResourcesDir:?}" || mkdir "${sourcesResourcesDir:?}"

### FIXME: --delete doesn't work below.
rsync -urtl --delete --files-from="${sourcesList:?}" --no-relative / "${sourcesResourcesDir:?}/${TARGET_NAME:?}/"
