#! /bin/sh -e

#  EmbedStaticFrameworkResources
#  GEXcodeBuildPhases
#
#  Created by Grigory Entin on 11.01.2018.
#  Copyright (c) 2018 Grigory Entin. All rights reserved.

rsync -urtl "${CONFIGURATION_BUILD_DIR:?}"/"${GE_STATIC_FRAMEWORK_RESOURCES_COLLECTOR_FOLDER_PATH:?}"/ "${TARGET_BUILD_DIR:?}/${UNLOCALIZED_RESOURCES_FOLDER_PATH:?}"/
