#! /bin/sh -e

#  EmbedStaticFrameworkResources
#  GEXcodeBuildPhases
#
#  Created by Grigory Entin on 11.01.2018.
#  Copyright (c) 2018 Grigory Entin. All rights reserved.

for i in "${CONFIGURATION_BUILD_DIR:?}" "${PROJECT_TEMP_ROOT:?}"/UninstalledProducts/"${PLATFORM_NAME:?}"
do
	testDir="$i"/"${GE_STATIC_FRAMEWORK_RESOURCES_COLLECTOR_FOLDER_PATH:?}"
	if [ -d "${testDir:?}" ]
	then
		resourcesDir="${testDir:?}"
	fi
done

rsync -urtl${GE_V_FOR_VERBOSE} "${resourcesDir:?}"/ "${TARGET_BUILD_DIR:?}/${UNLOCALIZED_RESOURCES_FOLDER_PATH:?}"/
