#! /bin/sh -e

#  IntegrateFabric
#  RSSReader
#
#  Created by Grigory Entin on 24.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

./Fabric.framework/run "${XC_FABRIC_API_KEY:?}" "${XC_FABRIC_BUILD_SECRET:?}"
