#! /bin/sh -e

#  IntegrateAppsee
#  RSSReader
#
#  Created by Grigory Entin on 24.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

./Appsee-upload_symbols.sh "${XC_APPSEE_API_KEY:?}"
