#! /bin/sh -e

#  RegenerateSBConstantsSwift
#  RSSReader
#
#  Created by Grigory Entin on 11.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

scriptName=$(basename "$0")
swiftrsrc=~/.toast/armed/bin/swiftrsrc
input="${SRCROOT:?}/${TARGET_NAME:?}"/Localizable/Base.lproj/Main.storyboard
output="${SRCROOT:?}/${TARGET_NAME:?}"/Swift/SBConstants.swift

if [ -x "${swiftrsrc:?}" ]
then
	tempOutput=$(mktemp /tmp/"${scriptName:?}".XXXXX)
	"${swiftrsrc:?}" generate "${input:?}" "${tempOutput:?}"
	if [ ! -f "${output:?}" ] || ! diff -q "${tempOutput:?}" "${output:?}"
	then
		cp -p "${tempOutput:?}" "${output:?}"
	fi
	rm "${tempOutput:?}"
fi
