#! /bin/sh -e

#  RegenerateSBConstantsSwift
#  RSSReader
#
#  Created by Grigory Entin on 11.01.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

gemUserDir="$(ruby -rubygems -e 'puts Gem.user_dir')"
sbconstants="${gemUserDir:?}"/bin/sbconstants
if [ -x "${sbconstants:?}" ]
then
	"${sbconstants:?}" --swift "${SRCROOT:?}/${TARGET_NAME:?}"/SBConstants.swift "${SRCROOT:?}/${TARGET_NAME:?}"/Base.lproj/Main.storyboard
fi
