#! /bin/sh -ex

#  UploadToFabric
#  RSSReader
#
#  Created by Grigory Entin on 11.02.15.
#  Copyright (c) 2015 Grigory Entin. All rights reserved.

ipa="${TARGET_BUILD_DIR:?}/${PRODUCT_NAME:?}.ipa"

if "${XC_UPLOAD_TO_FABRIC_ENABLED:?}" == "YES"
then
	./Crashlytics.framework/submit "${XC_FABRIC_API_KEY:?}" "${XC_FABRIC_BUILD_SECRET:?}" -ipaPath "${ipa:?}"
fi
